[target.x86_64-unknown-uefi]
runner = "cargo run -p runner"

[alias]
builder = "run --bin builder --features builder --quiet --"
runner = "run --bin runner --features builder --"

[env]
SECURE_BOOT = "ON"
